name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - name: Lerna setup
        run: npm install -g lerna@4 && npm install
      - name: Project install
        run: lerna bootstrap --scope=@astra-sdk/wallet-connect
      - name: ES5 build
        run: scripts/task babel
      - name: Publish
        run: cd packages/wallet-connector && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
